### ISSUE TITLE
multiple replication streams (client)

### ISSUE THREAD

**Issue by fsteff** [RangerMauve/discovery-swarm-stream#5]
Is it already possible to do replicate multiple feeds over one instance of the client proxy?
I saw in the code that ProxyStream should already support this, but how would this work with the client?

**Comment by fsteff** [comment]
Just found out that the native discovery-swarm does not support this as well.
(or at least dat-node uses one swarm per dat)

**Comment by RangerMauve** [comment]
Hypothetically you could use `hypercore-protocol` to replicate as many feeds as you want over a single proxied stream to a client.
